llm:
  default_model: "anthropic/claude-4.5-sonnet"
  max_tokens: 4096
  temperature: 0.7
  top_p: 1.0

processing:
  max_parallel_tasks: 5
  chunk_size: 2000
  overlap: 200
  max_retries: 3
  request_timeout: 60

quality:
  summary:
    min_words: 200
    max_words: 300
  takeaways:
    count: 5
    max_length: 200
  quotes:
    min_count: 3
    max_count: 10
  fact_checks:
    min_count: 3
    min_confidence: 0.6
  tags:
    min_count: 5
    max_count: 10

logging:
  level: "INFO"
  format: "json"
  reasoning_enabled: true
